### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by larchanka** [larchanka/tgcloud#1]
- [ ] User managements + request via bot
- [ ]  Fix drag-n-drop upload
- [x]  Add logout
- [ ]  Add comments to files
- https://www.npmjs.com/package/javascript-time-ago
- https://markdown-it.github.io/
- [ ]  Add files splitting
- [x] Check if owner or shared when view and download
- [ ] Rename categories
- [ ] Delete categories
